JOB_CATEGORIES = [
    "software_engineering",
    "data_science",
    "ai_and_agent_engineering",
    "electrical_engineering",
    "marketing",
    "finance",
    "human_resources",
    "education",
    "journalism_and_media",
    "biology_and_life_sciences",
    "engineering",
    "business_administration",
    "graphic_design",
    "psychology",
    "computer_science",
    "hospitality_and_tourism",
    "environmental_studies"
]